export const internal_sources = [
  {
    sourceType: "internal",
    title:
      "Tell me how Zomato is performing compared to swiggy on a operational and financial side and which has more growth opportunity",
    description: "Zomato – Initiating Coverage Note | Rating: ADD | ",
    filename: "Zomato_Initiating_Coverage",
    page_number: 20,
    summary:
      "This page provides a comparative analysis of Zomato and Swiggy's operations, highlighting their respective services and areas of focus. It also mentions potential future growth opportunities for these companies.",
  },
  {
    sourceType: "internal",
    title:
      "Tell me how Zomato is performing compared to swiggy on a operational and financial side and which has more growth opportunity",
    description: "Food delivery platform – Zomato vs. Swiggy\n\nA hori",
    filename: "Zomato_Initiating_Coverage",
    page_number: 39,
    summary:
      "This page compares the food delivery platforms Zomato and Swiggy, featuring a horizontal bar graphic with three segments. It was generated by Avendus Spark Research for a specific user.",
  },
  {
    sourceType: "internal",
    title:
      "Tell me how Zomato is performing compared to swiggy on a operational and financial side and which has more growth opportunity",
    description: "Zomato – Initiating Coverage Note | Rating: ADD | ",
    filename: "Zomato_Initiating_Coverage",
    page_number: 40,
    summary:
      "This page provides an analysis of Zomato's and Swiggy's restaurant listings and cuisine shares across major Indian cities. Zomato is shown to have higher listings and a detailed breakdown of cuisine preferences is provided for both platforms.",
  },
  {
    sourceType: "internal",
    title:
      "Tell me how Zomato is performing compared to swiggy on a operational and financial side and which has more growth opportunity",
    description: "SWIGGY | Initiating Coverage | Rating: ADD | TP: R",
    filename:
      "Initiating_Coverage_-_Swiggy_Rating__ADD_TP__Rs_360_-_Food_for_Thought_Groceries_on_Hold",
    page_number: 33,
    summary:
      "This page provides a comparison of services offered by Swiggy and its global peers, highlighting potential areas for expansion. It includes a detailed table of services across companies and notes on Swiggy's current initiatives.",
  },
  {
    sourceType: "internal",
    title:
      "Tell me how Zomato is performing compared to swiggy on a operational and financial side and which has more growth opportunity",
    description: "SWIGGY | Initiating Coverage | Rating: ADD | TP: R",
    filename:
      "Initiating_Coverage_-_Swiggy_Rating__ADD_TP__Rs_360_-_Food_for_Thought_Groceries_on_Hold",
    page_number: 26,
    summary:
      "This page provides a comparative analysis of Swiggy and Zomato, focusing on metrics like order frequency, market share, AOV, and GOV. It highlights Swiggy's stickier user base and premium positioning despite Zomato's higher market share and growth in tier 2&3 cities.",
  },
  {
    sourceType: "internal",
    title:
      "Tell me how Zomato is performing compared to swiggy on a operational and financial side and which has more growth opportunity",
    description: "Moderator: Ladies and gentlemen, good day and welc",
    filename: "Swiggy_Confcalltranscript_Q3FY25",
    page_number: 2,
    summary:
      "This document is a transcript of Swiggy Limited's third quarter FY2025 earnings conference call. It includes an introduction by the Head of Investor Relations, management commentary on competition and market dynamics, and a Q&A session addressing key business metrics and challenges.",
  },
];

export const web_sources = [
  {
    sourceType: "web",
    description:
      "Swiggy and Zomato are intensifying their rivalry in FY24, particularly in the quick-commerce sector. Swiggy’s Instamart and Zomato’s Blinkit are competing for dominance in grocery delivery, with Blinkit outperforming Instamart in gross order value (₹12,469 crore vs. ₹8,350 crore) and average order value (₹613 vs. ₹460). Blinkit’s focus on premium products and Delhi-NCR has contributed to its lead, while both companies are expanding their dark store networks to reduce delivery times.  \n\nSwiggy’s Instamart saw a 32% growth in monthly transacting users (MTUs) to 4.2 million, compared to Blinkit’s 5.1 million MTUs. However, Blinkit’s standalone app offers branding flexibility, whereas Instamart’s integration within Swiggy’s app enables cross-selling opportunities. Swiggy has improved profitability in Instamart, reducing its adjusted EBITDA loss margin from -39% in FY23 to -16% in FY24, aided by cost control and premium offerings.  \n\nSwiggy’s food delivery business achieved operational profitability, with gross revenues rising 17% to ₹6,100 crore. Zomato’s food delivery segment outpaced Swiggy, posting ₹7,792 crore in adjusted revenues and a positive EBITDA margin of 2.8%. Swiggy’s Dineout acquisition also showed promise, with GOV surging 98% to ₹2,200 crore.  \n\nSwiggy is preparing for a $1.25 billion IPO, aiming for a $15 billion valuation, while Zomato’s market capitalization stands at $26 billion. Both companies face challenges in scaling operations, achieving profitability, and competing with new entrants like Amazon and Flipkart. The next few years will be pivotal in determining which company solidifies its leadership in India’s food-tech and quick-commerce sectors.",
    url: "https://www.linkedin.com/pulse/swiggy-vs-zomato-food-delivery-quick-commerce-ipo-amit-varma-6skrc",
    title: "Swiggy vs Zomato: Quick Commerce and Profitability Battle",
  },
  {
    sourceType: "web",
    description:
      "Swiggy and Zomato, India's leading food delivery platforms, are under intense scrutiny as Swiggy recently debuted on the Indian stock market. Investors are evaluating both companies to identify the better investment opportunity.  \n\nIndia's online food delivery market is projected to grow at a CAGR of 20%, with limited new competition expected. However, quick commerce (QC) is emerging as a more lucrative segment, prompting food-tech companies to prioritize QC initiatives. This shift is expected to drive steady growth in gross order value (GOV) and sustainable profitability for both Swiggy and Zomato.  \n\nJM Financial's report favors Zomato for its superior execution and market leadership, suggesting a higher investment weightage for Zomato while also recommending exposure to Swiggy. Swiggy's IPO opened at ₹420 per share, a 7.69% premium, but saw a decline in delivery volumes and stock value post-listing. In contrast, Zomato's stock has surged 132% since its 2021 debut, outperforming its sector significantly.  \n\nAnalysts highlight operational efficiency and profitability as key differentiators. Zomato's consistent profits and potential inclusion in the Nifty 50 index are seen as growth catalysts. Conversely, Swiggy faces challenges with its loss-making dine-out service, which lacks a clear path to profitability.  \n\nDespite their rivalry, both companies share identical growth drivers, targeting the same market. Analysts like Prashanth Tapse advocate diversifying investments across both firms to capitalize on the sector's expansion. However, concerns about competition from well-funded players like Zepto and Amazon, as well as the socio-economic impact of QC on traditional Kirana stores, add complexity to the industry's outlook.  \n\nOverall, Zomato appears better positioned for long-term gains, but Swiggy's IPO proceeds could enhance its operational performance, making both companies attractive in a rapidly growing market.",
    url: "https://www.livemint.com/market/stock-market-news/swiggy-and-zomato-what-should-be-your-strategy-for-these-two-new-age-tech-stocks-11731905549529.html",
    title: "Swiggy vs Zomato: Investment Insights and Market Dynamics",
  },
  {
    sourceType: "web",
    description:
      "The Indian food delivery market is dominated by two giants, Zomato and Swiggy, operating in a competitive duopoly. Both platforms offer similar services, including food delivery, subscriptions, and partnerships with restaurants, but their strategies differ significantly.  \n\nZomato, founded in 2008, has expanded from restaurant discovery to food delivery, cloud kitchens, and international markets. Its Zomato Pro subscription and focus on high-margin services like restaurant advertising and cloud kitchens have driven strong revenue growth and profitability. By FY24, Zomato reported a revenue of Rs 121.14 billion and a net profit of Rs 3.51 billion, with a market share of 58%.  \n\nSwiggy, launched in 2014, has diversified into grocery delivery (Instamart), local errands (Genie), and restaurant reservations (Dineout). While its revenue grew to Rs 116.34 billion in FY24, Swiggy remains unprofitable, with a net loss of Rs 23.50 billion. Its market share has declined to 34%, partly due to its focus on quick commerce.  \n\nZomato outperforms Swiggy in key metrics like Average Revenue Per User (ARPU), Gross Merchandise Value (GMV), and Monthly Transacting Users (MTUs). However, Swiggy is more cost-efficient in customer acquisition.  \n\nBoth companies face challenges, including high customer acquisition costs, competition from emerging players, and regulatory pressures. While Zomato's profitability and market leadership make it a stronger investment choice, Swiggy's diversified offerings position it as a resilient competitor.  \n\nAs the food delivery market grows, driven by changing consumer habits and smartphone penetration, both players are poised to benefit, though profitability remains a key hurdle.",
    url: "https://www.equitymaster.com/detail.asp?date=11/07/2024&story=5&title=Swiggy-vs-Zomato-The-Battle-for-Your-Next-Meal-%2D-Who-Are-You-Choosing",
    title: "Swiggy vs Zomato: India's Food Delivery Duopoly",
  },
  {
    sourceType: "web",
    description:
      "Swiggy’s Rs 11,300 crore IPO has intensified competition with Zomato in India’s rapidly growing food delivery and quick commerce market. The sector is projected to grow at a 20% CAGR from 2023 to 2028, with quick commerce, led by groceries, expected to expand at 60-80% annually.  \n\nZomato currently dominates with a 58% market share in food delivery and 40-45% in quick commerce. After overcoming skepticism about its valuations and losses, Zomato has posted four consecutive profitable quarters, achieving positive EBITDA in its quick commerce arm, Blinkit. This financial turnaround has boosted its stock by 120% in 2023, reflecting strong investor confidence.  \n\nSwiggy, on the other hand, remains unprofitable, reporting a Rs 2,350 crore loss in FY24. However, its IPO aims to close the valuation gap with Zomato by funding expansion, particularly in its quick commerce segment, including setting up a Dark Store network. Analysts expect Swiggy to focus on profitability post-IPO, mirroring Zomato’s strategy.  \n\nWhile Zomato has demonstrated stronger market traction with a gross order value CAGR of 23% compared to Swiggy’s 15.5%, Swiggy’s IPO is priced at a meaningful discount, making it an attractive option for investors. Experts suggest diversifying investments between the two companies, given the duopoly nature of the market and its high growth potential.  \n\nIn the long term, both companies are expected to achieve healthy profitability, with Swiggy potentially leveraging IPO funds for faster growth. Analysts recommend a 70% allocation to Swiggy for its growth potential and 30% to Zomato for its proven performance.",
    url: "https://m.economictimes.com/markets/stocks/news/swiggy-ipo-vs-zomato-which-is-the-better-investment-option-currently/articleshow/114999413.cms",
    title: "Swiggy vs Zomato: Investment Prospects in Food Delivery",
  },
  {
    sourceType: "web",
    description:
      "Swiggy, a leading food and grocery delivery platform, is launching its IPO on November 6, aiming to raise ₹11,327.43 crore. The offering includes a fresh issue of ₹4,499 crore and an offer-for-sale (OFS) worth ₹6,828.43 crore, with shares priced between ₹371 and ₹390. At the upper price band, Swiggy’s valuation reaches $11.3 billion, slightly above its 2022 funding round valuation.  \n\nSwiggy’s main competitor, Zomato, went public in 2021 with a $13 billion valuation and has since grown to over $25 billion in market value by 2024. Despite recent stock pressure, Zomato has delivered strong returns, with a 95% year-to-date increase and a 285% gain over two years.  \n\nAnalysts highlight key differences between the two companies. Zomato has achieved profitability and leads in metrics like average order value (AOV) and gross order value (GOV), with a robust 23% CAGR compared to Swiggy’s 15.5%. Swiggy, however, has been incurring losses for three consecutive years, raising concerns about its ability to turn profitable.  \n\nExperts like Akriti Mehrotra and Anshul Jain suggest caution regarding Swiggy’s IPO. They note that a significant portion of the IPO is an OFS, allowing early investors to exit at high prices. With Zomato offering similar revenue but greater profitability and stability, analysts recommend investing in Zomato over Swiggy.  \n\nWhile Swiggy’s IPO provides exposure to the growing food and quick commerce sectors, its uncertain path to profitability and competition with Zomato make it a riskier choice for investors.",
    url: "https://www.5paisa.com/news/swiggy-vs-zomato-is-swiggys-ipo-worth-subscribing-to-or-is-zomato-the-better-buy",
    title: "Swiggy IPO Launch: Competition with Zomato and Investor Caution",
  },
];

export const deep_web_sources = [
  {
    sourceType: "web",
    title: "",
    description:
      "EBITDA Over Time\n\nPBIDT stands for Profit Before Interest, Depreciation, and Taxes. It is a financial metric that measures a company's profitability before accounting for interest expenses, depreciation of assets, and taxes. Formula to calculate PBIDT: PBIDT = Net Income + Interest + Depreciation + Taxes or PBIDT = Operating Income + Depreciation + Taxes PBIDT vs EBITDA vs EBIT vs EBT: Here is a brief explanation of the differences: - PBIDT (Profit Before Interest, Depreciation, and Taxes) includes taxes in its calculation, unlike EBITDA. - EBITDA (Earnings Before Interest, Taxes, Depreciation, and Amortization) excludes taxes and interest, focusing on operational performance. - EBIT (Earnings Before Interest and Taxes) excludes interest and taxes, providing a measure of core operational profitability. - EBT (Earnings Before Taxes) includes all operating income but does not account for interest expenses. Conclusion: PBIDT, similar to EBITDA, is a measure of operational profitability but includes taxes in its calculation.",
    url: "https://blinkx.in/insights/stock-comparison/swiggy-ltd-vs-zomato-ltd",
    query:
      "**Financial Performance**: How do Swiggy and Zomato compare in terms of revenue growth, profitability (EBITDA margins), cash burn rates, and funding history over the last three years?",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "The IPO of Swiggy has been cleared by the market regulator and the issue could hit the public market anytime. Meanwhile, the IPO has also thrown some spotlight on its competitor and listed peer Zomato. Given such intense scrutiny, here's a comparison of financials of both these companies in the last three fiscal years. [Source: Annual reports, Company reports] Note: Brackets indicate loss",
    url: "https://m.economictimes.com/markets/stocks/news/swiggy-vs-zomato-who-is-winning-the-financial-race/adjusted-ebitda/loss/slideshow/113836605.cms",
    query:
      "**Financial Performance**: How do Swiggy and Zomato compare in terms of revenue growth, profitability (EBITDA margins), cash burn rates, and funding history over the last three years?",
  },
  {
    sourceType: "web",
    title: "Zomato vs Swiggy: Who Leads India's Delivery Market?",
    description:
      "Zomato and Swiggy dominate India's food and grocery delivery market, but Zomato appears to have the upper hand based on recent data. In FY25, Zomato’s parent company, Eternal, reported a 67% YoY revenue growth to ₹20,243 crore, surpassing Swiggy’s ₹15,227 crore revenue, which grew 35%. Zomato also achieved a profit of ₹527 crore, while Swiggy faced a loss of ₹3,117 crore.\n\nZomato leads in customer base, with 2.09 crore monthly food delivery users compared to Swiggy’s 1.51 crore. In quick commerce, Zomato’s Blinkit processes 15.7 lakh daily orders, exceeding Swiggy’s Instamart by 3.6 lakh orders. Blinkit also boasts a higher average order value (₹665 vs ₹527) and more dark stores (1,301 vs 1,021). Blinkit’s sales grew 126% YoY to ₹5,206 crore, while Instamart grew 118% to ₹2,130 crore. Blinkit significantly reduced losses by 92%, whereas Instamart’s losses increased by 60%.\n\nMarket analysts estimate Zomato holds a 55-58% share in food delivery, compared to Swiggy’s 42-45%. Investors show greater confidence in Zomato, reflected in its higher Price-to-Sales ratio (12.2 vs 6) and better stock performance. Zomato’s profitability and faster growth in both food delivery and quick commerce give it a competitive edge.\n\nHowever, concerns about duopoly persist, with both companies controlling over 90% of the market, potentially leading to higher costs for restaurants and consumers. Emerging platforms like ONDC may challenge this dominance. While Zomato currently leads, Swiggy’s investments in quick commerce could yield future growth opportunities.",
    url: "https://www.indmoney.com/blog/stocks/swiggy-vs-zomato-fy25",
    query:
      "**Financial Performance**: How do Swiggy and Zomato compare in terms of revenue growth, profitability (EBITDA margins), cash burn rates, and funding history over the last three years?",
  },
  {
    sourceType: "web",
    title: "Swiggy vs Zomato: Investment Insights and Market Dynamics",
    description:
      "Swiggy and Zomato, India's leading food delivery platforms, are under intense scrutiny as Swiggy recently debuted on the Indian stock market. Investors are evaluating both companies to identify the better investment opportunity.  \n\nIndia's online food delivery market is projected to grow at a CAGR of 20%, with limited new competition expected. However, quick commerce (QC) is emerging as a more lucrative segment, prompting food-tech companies to prioritize QC initiatives. This shift is expected to drive steady growth in gross order value (GOV) and sustainable profitability for both Swiggy and Zomato.  \n\nJM Financial's report favors Zomato for its superior execution and market leadership, suggesting a higher investment weightage for Zomato while also recommending exposure to Swiggy. Swiggy's IPO opened at ₹420 per share, a 7.69% premium, but saw a decline in delivery volumes and stock value post-listing. In contrast, Zomato's stock has surged 132% since its 2021 debut, outperforming its sector significantly.  \n\nAnalysts highlight operational efficiency and profitability as key differentiators. Zomato has consistently generated profits and is set to enter the Futures & Options market, potentially boosting investor interest. Speculation about its inclusion in the Nifty 50 index further enhances its outlook. Swiggy, however, faces challenges with its loss-making dine-out service, which lacks a clear path to profitability.  \n\nBoth companies face external pressures from well-funded competitors like Zepto, Flipkart, and Amazon, which could strain margins. Additionally, the rise of QC threatens traditional Kirana stores, impacting millions of livelihoods.  \n\nWhile Zomato appears better positioned for long-term growth, Swiggy's recent IPO and capital infusion could improve its performance. Analysts recommend diversifying investments across both companies to capitalize on the sector's rapid expansion.",
    url: "https://www.livemint.com/market/stock-market-news/swiggy-and-zomato-what-should-be-your-strategy-for-these-two-new-age-tech-stocks-11731905549529.html",
    query:
      "Tell me how Swiggy is performing compared to Zomato on a operational and financial side and which has more growth opportunity",
  },
  {
    sourceType: "web",
    title: "Swiggy vs Zomato: Investment Prospects in Food Delivery",
    description:
      "Swiggy’s Rs 11,300 crore IPO has intensified competition with Zomato in India’s rapidly growing food delivery and quick commerce market. The sector is projected to grow at a 20% CAGR from 2023 to 2028, with groceries dominating quick commerce. Zomato leads the market with a 58% share in food delivery and 40-45% in quick commerce, supported by four profitable quarters and a 120% stock surge this year. Analysts highlight Zomato’s stronger market traction, with a gross order value CAGR of 23% compared to Swiggy’s 15.5%.\n\nSwiggy, however, aims to close the profitability gap post-IPO by reducing promotional expenses and investing Rs 1,178 crore into expansion and its Dark Store network for quick commerce. Despite reporting a Rs 2,350 crore loss in FY24, Swiggy’s IPO offers a discounted valuation compared to Zomato, making it an attractive option for investors. Analysts suggest Swiggy could leverage IPO funds to improve operational metrics and compete more effectively.\n\nBoth companies operate in a duopoly market with significant growth potential, and experts recommend diversifying investments between the two. While Zomato has proven its profitability, Swiggy’s fresh capital injection could drive faster growth. For long-term shareholder value, analysts propose allocating 70% of funds to Swiggy and 30% to Zomato, balancing proven performance with future potential.",
    url: "https://m.economictimes.com/markets/stocks/news/swiggy-ipo-vs-zomato-which-is-the-better-investment-option-currently/articleshow/114999413.cms",
    query:
      "Tell me how Swiggy is performing compared to Zomato on a operational and financial side and which has more growth opportunity",
  },
  {
    sourceType: "web",
    title: "Swiggy IPO: Opportunity or Risk Amid Zomato Rivalry?",
    description:
      "Swiggy, a leading food and grocery delivery platform, is launching its IPO on November 6, aiming to raise ₹11,327.43 crore. The offering includes a fresh issue worth ₹4,499 crore and an offer-for-sale (OFS) of ₹6,828.43 crore, priced between ₹371 and ₹390 per share, valuing the company at $11.3 billion. This valuation slightly exceeds its last funding round in 2022. Swiggy’s IPO comes amid comparisons with its competitor Zomato, which went public in 2021 and has since achieved profitability and significant stock growth, with a market capitalization of over $25 billion by 2024.\n\nAnalysts highlight key differences between the two companies. Zomato boasts superior financial metrics, including higher average order value (AOV), gross order value (GOV), and market share, alongside a profitable business model. In contrast, Swiggy has reported losses for three consecutive years, raising concerns about its ability to achieve profitability. Experts like Akriti Mehrotra and Anshul Jain suggest caution regarding Swiggy’s IPO, noting that a significant portion of the offering is an OFS, allowing early investors to exit at high prices. They recommend considering Zomato shares instead, given its stable revenue and profit clarity.\n\nWhile Swiggy’s IPO offers exposure to the growing food delivery and quick commerce sectors, its uncertain path to profitability and competitive disadvantages compared to Zomato may deter investors. Analysts advise weighing the risks and rewards carefully before investing.",
    url: "https://www.5paisa.com/news/swiggy-vs-zomato-is-swiggys-ipo-worth-subscribing-to-or-is-zomato-the-better-buy",
    query:
      "Tell me how Swiggy is performing compared to Zomato on a operational and financial side and which has more growth opportunity",
  },
  {
    sourceType: "web",
    title: "Swiggy vs Zomato: Quick Commerce and Profitability Battle",
    description:
      "Swiggy and Zomato are intensifying their rivalry in FY24, particularly in the quick-commerce sector. Swiggy’s Instamart and Zomato’s Blinkit are competing for dominance in grocery delivery, with Blinkit outperforming Instamart in gross order value (₹12,469 crore vs. ₹8,350 crore) and average order value (₹613 vs. ₹460). Blinkit’s focus on premium products and Delhi-NCR has contributed to its lead, while both companies are expanding their dark store networks to reduce delivery times.  \n\nSwiggy’s Instamart saw a 32% growth in monthly transacting users (MTUs) to 4.2 million, compared to Blinkit’s 5.1 million MTUs. However, Blinkit’s standalone app offers branding flexibility, whereas Instamart’s integration within Swiggy’s app enables cross-selling opportunities. Swiggy has also improved profitability in Instamart, reducing its adjusted EBITDA loss margin from -39% in FY23 to -16% in FY24.  \n\nSwiggy’s food delivery segment achieved operational profitability, with gross revenues rising 17% to ₹6,100 crore. Zomato’s food delivery business outpaced Swiggy, posting ₹7,792 crore in adjusted revenues and a positive EBITDA margin of 2.8%. Swiggy’s Dineout acquisition boosted its restaurant reservation business, while Zomato diversified into ticketing through Paytm’s ticketing arm.  \n\nSwiggy is preparing for a $1.25 billion IPO, aiming for a $15 billion valuation. The company’s focus on cost control, category expansion, and higher average order values positions it for growth, though competition from Zomato and new entrants like Amazon and Flipkart remains fierce. Both companies are at critical junctures, with their paths to profitability and market leadership diverging as they expand into adjacent categories.",
    url: "https://www.linkedin.com/pulse/swiggy-vs-zomato-food-delivery-quick-commerce-ipo-amit-varma-6skrc",
    query:
      "Tell me how Swiggy is performing compared to Zomato on a operational and financial side and which has more growth opportunity",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Swiggy is all set to launch its IPO, and it has filed DRHP (Draft Red Herring Prospectus) with SEBI. But, what actually is a DRHP? It is a detailed document containing all the information about the company that helps investors make informed decisions. You can think of it as a treasure, containing almost every information from the company's business model and financials, to the risks associated. DRHP includes: -IPO details and information on fresh issue and offer for sale (OFS) -Company's Business Model and Industry Overview -Risks associated -Financial Statements -Management information -Use of Proceeds ✨ Key Highlights of DRHP: -Although, revenue from operations has been increasing each year, Swiggy has been incurring losses, since incorporation and have negative cash flows from operations, driven by a surge in advertisement and promotional expenses to expand the user base and enhance the brand presence, with delivery related costs, employee benefit expenses, being among others. - 📈 However, their revenue from the food delivery operations have improved from a loss of ₹337.76 million in the three months ended June 30, 2023 to a profit of ₹674.02 million in the three months ended June 30, 2024, which is definitely a significant improvement, in their food delivery segment. - 💲 Average Order Value (AOV): Food Delivery: ₹428 Instamart: ₹460 Dineout: ₹3,129 -💼 Operational Scale: Swiggy works with 223,671 monthly transacting restaurant partners and 457,249 monthly transacting delivery partners, reflecting its massive operational scale and reach. It would be interesting to see how Swiggy will compete with Zomato going forward and the impact on the stock prices as well. Let me know what do you guys think on this!",
    url: "https://www.linkedin.com/posts/contact-me-tushaar_swiggy-ipo-how-does-its-valuation-compare-activity-7257338392219144192-x88X",
    query:
      "**Valuation and Investor Sentiment**: How do investors perceive Swiggy and Zomato in terms of valuation, growth potential, and risk? Are there any recent funding rounds, IPO updates, or analyst reports that provide insights into their future trajectories?",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "In Brief\n\nSwiggy, one of India’s largest food delivery and quick-commerce startups, is seeking a valuation of up to $11.3 billion in its initial public offering, marking a 57% discount to rival Zomato’s market cap.\n\nThe lossmaking Bengaluru-based company has set an IPO price band of ₹371 to ₹390 ($4.41 to $4.64) per share for next month’s IPO. At the upper end, the valuation would represent only a modest premium to its $10.7 billion private market value from early 2022 — falling short of recent valuations by mutual fund investors Invesco and Baron.\n\nSwiggy aims to raise $1.34 billion, with $535 million from fresh share issuance and the remainder through existing investor exits. Swiggy, which led India’s food delivery market four years ago and pioneered quick commerce, has since lost significant market share in both segments. In quick commerce, it now ranks third behind Zomato’s Blinkit and Nexus-backed Zepto.\n\nZomato, which recently announced plans to raise up to $1 billion through a qualified institutional placement, currently commands a market cap of $26.2 billion.",
    url: "https://techcrunch.com/2024/10/30/once-dominant-swiggy-seeks-11-3b-value-at-ipo-less-than-half-zomatos-worth/",
    query:
      "**Valuation and Investor Sentiment**: How do investors perceive Swiggy and Zomato in terms of valuation, growth potential, and risk? Are there any recent funding rounds, IPO updates, or analyst reports that provide insights into their future trajectories?",
  },
  {
    sourceType: "web",
    title: "Zomato's IPO Valuation and Market Dynamics",
    description:
      "Zomato's initial public offering (IPO) in July 2021 saw its stock debut at ₹74 per share, far exceeding the author's valuation of ₹41 per share. The stock soared to ₹169 by late 2021, driven by market enthusiasm and momentum, despite the company reporting escalating losses and facing governance challenges. However, by July 2022, the stock price had dropped to ₹41.65, reflecting disappointing financial results, macroeconomic pressures, and negative sentiment following Zomato's acquisition of Blinkit for ₹4400 crores.  \n\nThe author revisited Zomato's fundamentals, noting positive developments such as market growth, Zomato's strong market share, and its cash cushion from the IPO. However, challenges persist, including declining take rates, ballooning losses, and questions surrounding the efficiency of its acquisition-driven growth strategy. Additionally, macroeconomic factors like rising inflation and higher equity risk premiums have increased Zomato's cost of capital, further impacting its valuation.  \n\nIn a revaluation conducted in July 2022, the author estimated Zomato's intrinsic value at ₹35.32 per share, down from ₹40.79 in 2021. While the stock's current price of ₹41.65 exceeds this valuation, the author suggests buying Zomato if the price drops below the median value of ₹34.12, as part of a diversified portfolio. Traders, however, are advised to focus on mood and momentum rather than intrinsic value.  \n\nThe author concludes by emphasizing the importance of taking ownership of investment decisions, cautioning against attributing losses to external factors like market conspiracies or financial analysts. Instead, investors should learn from their experiences and avoid relying solely on momentum-driven strategies.",
    url: "https://aswathdamodaran.substack.com/p/a-zomato-2022-update-price-value",
    query:
      "**Valuation and Investor Sentiment**: How do investors perceive Swiggy and Zomato in terms of valuation, growth potential, and risk? Are there any recent funding rounds, IPO updates, or analyst reports that provide insights into their future trajectories?",
  },
  {
    sourceType: "web",
    title: "Swiggy’s IPO: Growth, Challenges, and Strategic Outlook",
    description:
      "Swiggy, a leading player in India’s food delivery and quick commerce sectors, recently debuted on the stock market, raising questions about its long-term sustainability in a competitive and capital-intensive industry. The company’s strengths include its innovative services like Bolt (10-minute deliveries), a loyal customer base through Swiggy One, and a robust network of restaurants and stores. However, it faces intense competition from Zomato, Zepto, and Flipkart Quick, as well as challenges from regulatory pressures and customer power in a crowded market.  \n\nSwiggy operates in a rapidly growing quick commerce market, projected to reach $30-50 billion in the coming years. With a current market share of 15%, Swiggy aims to expand to 25% by scaling its dark store capacity, entering new cities, and diversifying into categories like pharma and daily meals. Despite its growth potential, Swiggy must protect its competitive edge by continuously innovating and addressing ESG concerns, particularly the treatment of gig workers.  \n\nThe company’s management, led by CEO Sriharsha Majety, has demonstrated a focus on long-term growth, with plans to achieve profitability in quick commerce by December 2025. While Swiggy’s revenue is growing steadily (30% YoY), it remains unprofitable, with improving margins signaling progress. Its valuation (EV/GOV of 2.45x) appears higher than Zomato’s, reflecting optimism about its future.  \n\nSwiggy’s real options—expanding into new services, abandoning underperforming initiatives, and timing investments strategically—add significant value. However, risks include intense competition, regulatory changes, and profitability challenges. If Swiggy continues to innovate and execute its growth strategy effectively, it has the potential to solidify its leadership in food delivery and quick commerce. For now, a cautious “hold” recommendation is advised, with a medium-term outlook to assess its post-IPO performance.",
    url: "https://www.linkedin.com/pulse/swiggys-post-ipo-journey-valuation-insights-future-raja-chidambaram-ifeec",
    query:
      "**Valuation and Investor Sentiment**: How do investors perceive Swiggy and Zomato in terms of valuation, growth potential, and risk? Are there any recent funding rounds, IPO updates, or analyst reports that provide insights into their future trajectories?",
  },
  {
    sourceType: "web",
    title: "Swiggy’s IPO: Challenges in Competing with Zomato",
    description:
      "Swiggy’s $11 billion IPO marks a pivotal moment in India’s food-tech sector as it seeks to challenge Zomato’s dominance in food delivery and quick commerce. The IPO, which raised $1.36 billion, reflects Swiggy’s growth ambitions but also highlights concerns about its unprofitable status and market position. Initially targeting a $15 billion valuation, Swiggy adjusted its price band to $4.44-$4.67 per share amid market uncertainty, with $540 million in fresh shares and $820 million in an Offer for Sale by early investors like Accel and Prosus.  \n\nInstitutional investors, including Fidelity and Norges Bank, showed strong interest, with the Qualified Institutional Buyers (QIB) segment oversubscribed by 140%. However, retail investors were more cautious, with only 97% subscription, and non-institutional interest lagged at 0.38%. The grey market premium fell from 4% to below 1% by the IPO’s close, reflecting tepid sentiment compared to Zomato’s high-demand IPO in 2021.  \n\nSwiggy’s financials reveal growing revenues but persistent losses. In FY24, it reported $1.36 billion in revenue but a $283 million net loss. In contrast, Zomato achieved a $42 million net profit in the same period. Swiggy’s heavy investments in quick-commerce service Instamart and delivery platform Genie have yet to yield profitability, with analysts warning these ventures may require years to break even.  \n\nZomato leads the market with a 58% share in food delivery and 40-45% in quick commerce, compared to Swiggy’s 34% and 20-25%, respectively. Analysts remain cautious about Swiggy’s high valuation and unprofitable status, with mixed recommendations on its IPO. While Swiggy’s revenue growth signals potential, its ability to achieve sustainable profitability and compete with Zomato remains uncertain.",
    url: "https://techfundingnews.com/can-swiggys-11b-ipo-compete-with-zomatos-market-presence-all-you-need-to-know/",
    query:
      "**Valuation and Investor Sentiment**: How do investors perceive Swiggy and Zomato in terms of valuation, growth potential, and risk? Are there any recent funding rounds, IPO updates, or analyst reports that provide insights into their future trajectories?",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Crisp and short\n\nWe value your time. Our reporting and analysis focus on what’s important.",
    url: "https://www.thearcweb.com/article/swiggy-prosus-ipo-zomato-food-delivery-rnzRqOM9ONEFwojN",
    query:
      "**Operational Metrics Analysis**: What are the key operational metrics (e.g., order volume, delivery time, customer retention rates, and market share) for Swiggy and Zomato, and how do they compare across major markets in India?",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Have been facing very bad customer experiences from Zomato past 10 days. 3 times I had the wrong update about delivery time and my day good spoiled. I really don't understand, with so much technology being developed and so much of investments being made in technology why these companies are not able to update the real delivery time with approximate accuracy. I have been using Zomato only for the past couple of years or so, but now this has made me think of switching over to Swiggy again [don't know if Swiggy has the same problem too]. One day I ordered from Zomato Everyday just for the reason that they deliver under 20 mins. The order got delayed and took almost 50 mins after which I got frustrated and cancelled the order. Today morning ordered food at 8.16 AM with an estimated delivery time of 34 mins which is 8.50 AM. When checking at 9.05 AM the estimated time is still 22 mins with a comment delay in picking up. I am a Zomato Gold user and in most of the delays I have observed, they are trying to group the order which is causing the delay. I am not against grouping, but if you tell me upfront it will take 1 hour, I won't order from that hotel. I get too disturbed when the food gets delayed mainly due to severe acidity and heartburn and second I plan an order food to match my meeting and office time. All these get disturbed. Is anyone else facing a similar issue or is Swiggy better in this aspect?",
    url: "https://www.linkedin.com/posts/sonali-bhardwaj_i-explored-6-products-across-zomato-to-linkedin-activity-7226169877986787329-nmAH",
    query:
      "**Operational Metrics Analysis**: What are the key operational metrics (e.g., order volume, delivery time, customer retention rates, and market share) for Swiggy and Zomato, and how do they compare across major markets in India?",
  },
  {
    sourceType: "web",
    title: "Zomato: Evolution, Strategy, and Market Leadership",
    description:
      "Founded in 2008 by Deepinder Goyal and Pankaj Chaddah, Zomato has grown from a restaurant discovery platform to a global food delivery and quick commerce leader. Initially named FoodieBay, it rebranded to Zomato to avoid confusion with eBay. By 2015, Zomato entered food delivery, achieving unicorn status in 2018 and going public in 2021 with an $8 billion valuation. Today, Zomato operates across food delivery, dining-out services, and grocery delivery via Blinkit, which it acquired in 2022.  \n\nZomato’s competitive edge lies in reliability, service quality, and its extensive network of 276,000 restaurant partners. Its average delivery time of 12.5 minutes and fulfillment accuracy of over 99% highlight its operational efficiency. The company’s focus on Northern Indian metros, particularly Delhi NCR, ensures strong market penetration.  \n\nIndia’s food services market, valued at ₹5.5 lakh crores, is growing at an 18% CAGR in online food delivery, with Zomato holding a 55% market share. Quick commerce, valued at $2.8 billion, is also expanding rapidly, driven by urbanization and demand for convenience. Zomato’s Blinkit leads this segment with a 45% market share.  \n\nZomato’s revenue model includes delivery fees, restaurant commissions, and B2B supplies via Hyperpure. In FY 2023-24, Zomato’s revenue grew by 50% to ₹13,545 crores, with food delivery contributing ₹32,224 crores in Gross Order Value (GOV). The company has achieved profitability in quick commerce and reduced losses in its B2B segment.  \n\nZomato’s customer acquisition strategies include SEO-driven content, meme marketing, and partnerships with platforms like IRCTC and PhonePe. Its engagement initiatives, such as Zomato Social, aim to enhance user retention and monetization. With a focus on reliability, innovation, and market leadership, Zomato continues to redefine India’s food delivery and quick commerce landscape.",
    url: "https://growthx.club/blog/zomato-business-model",
    query:
      "**Operational Metrics Analysis**: What are the key operational metrics (e.g., order volume, delivery time, customer retention rates, and market share) for Swiggy and Zomato, and how do they compare across major markets in India?",
  },
  {
    sourceType: "web",
    title: "End-to-End Predictive Analysis of Zomato's Business Model",
    description:
      "Zomato, a leading food delivery aggregator founded in 2008, has evolved from a restaurant recommendation platform (Foodiebay) to a multifaceted business with over 100 million downloads. Competing with Swiggy, Zomato maintains an edge with a higher Average Order Value (AOV), a critical metric for profitability. The company has diversified its offerings through strategic acquisitions like Grofers for grocery delivery and initiatives like Hyperpure, which supplies ingredients to restaurants. Hyperpure has shown significant revenue growth, though it faces competition from local traders.  \n\nZomato Pro and Pro Plus subscriptions aim to enhance customer loyalty, while Zomato for Work targets corporate catering. Zomato Kitchens supports cloud kitchens, providing infrastructure and sharing profits with partner restaurants. Other ventures include app listings, table reservations, advertisements, and events like Zomaland. Despite these expansions, the online delivery segment remains a major cash burn, with profitability hinging on increasing AOV above Rs 500.  \n\nData analysis reveals that Zomato's Indian operations dominate its dataset, with North Indian cuisine being the most popular. U.S. restaurants have higher ratings and votes, indicating better service and customer engagement. Price range 1 restaurants in India, while affordable, challenge Zomato's unit economics. Ratings correlate positively with average costs, suggesting premium restaurants receive better feedback.  \n\nPredictive analytics at Zomato addresses operational challenges like delivery time, order volume, and customer satisfaction. Machine learning models can optimize metrics like AOV, delivery costs, and restaurant segmentation. Business case studies explore strategies to enhance profitability, customer retention, and operational efficiency.  \n\nZomato's data-driven approach underscores the importance of analytics in refining its business model, improving customer experience, and achieving financial sustainability.",
    url: "https://www.analyticsvidhya.com/blog/2021/10/end-to-end-predictive-analysis-on-zomato/",
    query:
      "**Operational Metrics Analysis**: What are the key operational metrics (e.g., order volume, delivery time, customer retention rates, and market share) for Swiggy and Zomato, and how do they compare across major markets in India?",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "In a strategic shift to broaden their offerings beyond food and grocery delivery, industry heavyweights Swiggy and Zomato are exploring new ventures that could reshape their business models, according to a report in The Economic Times.\n\nSwiggy, based in Bengaluru and set to list on the stock exchange on November 13, is preparing to pilot a new services marketplace named 'Yello.' The platform will host various professionals, including lawyers, therapists, fitness trainers, astrologers, and dietitians. Swiggy is still deliberating whether to incorporate Yello into its man app or launch it as a separate entity, insiders reveal.\n\nAdditionally, Swiggy is testing a premium membership service, 'Rare Club', aimed at affluent customers. This service offers exclusive access to high-profile events like Formula 1 races, concerts, upscale art exhibitions, VIP hospitality, and priority bookings at luxury restaurants. The main Swiggy app currently integrates food delivery, quick commerce through Instamart, Dineout, and hyperlocal delivery service Swiggy Genie.\n\nMeanwhile, Zomato is also exploring new paths to engage customers. The Gurgaon-based company is piloting a concierge-like food ordering service on WhatsApp, where human customer service agents will handle orders, moving away from its reliance on chatbots. This new approach could redefine Zomato's customer service experience, making it more personalized.\n\nBoth companies' diversification plans highlight the intensifying competition in the e-commerce space, where they face rivals like Flipkart, Amazon, and newer entrants such as Zepto in the quick-commerce sector.\n\nZomato, which acquired Paytm's events and ticketing business for Rs 2,048 crore, also plans to expand its platform for handymen services, competing with NCR-based Urban Company. Zomato's Blinkit, another diversification play, is expected to enhance its service offerings with home services like plumbing, electrical work, and carpentry.\n\nThe need for continuous innovation in these markets is underscored by analysts who believe that while Swiggy and Zomato's core businesses have stabilized, the rapid growth trajectory may eventually taper off, particularly as food and quick commerce delivery matures.\n\nZomato, valued at ₹2.2 lakh crore, closed at ₹249.10 on the BSE on November 8, while Swiggy’s IPO saw the firm valued at approximately ₹95,000 crore. Swiggy's diversification strategy contrasts with Zomato’s approach of creating distinct brands for its expanding portfolio, including its food delivery service and Instamart.",
    url: "https://www.storyboard18.com/brand-marketing/swiggy-and-zomato-eye-new-frontiers-in-diversification-46944.htm",
    query:
      "**Diversification and Strategic Initiatives**: How do Swiggy and Zomato differ in their diversification strategies (e.g., Swiggy Instamart vs. Zomato’s Hyperpure and Blinkit acquisition)? What impact do these initiatives have on their long-term growth potential?",
  },
  {
    sourceType: "web",
    title: "Swiggy vs Zomato: Quick Commerce and Profitability Battle",
    description:
      "Swiggy and Zomato are intensifying their rivalry in FY24, particularly in the quick-commerce sector. Swiggy’s Instamart and Zomato’s Blinkit are competing for dominance in grocery delivery, with Blinkit outperforming Instamart in gross order value (₹12,469 crore vs. ₹8,350 crore) and average order value (₹613 vs. ₹460). Blinkit’s focus on premium products and Delhi-NCR has contributed to its lead, while both companies are expanding their dark store networks to reduce delivery times.  \n\nSwiggy’s Instamart saw a 32% growth in monthly transacting users (MTUs), reaching 4.2 million, compared to Blinkit’s 5.1 million MTUs. However, Blinkit’s standalone app offers branding flexibility, whereas Instamart’s integration within Swiggy’s app enables cross-selling opportunities. Swiggy has also improved profitability in Instamart, reducing its adjusted EBITDA loss margin from -39% in FY23 to -16% in FY24.  \n\nSwiggy’s food delivery segment remains a key revenue driver, contributing 70% of its gross order value (₹35,272 crore). The segment achieved operational profitability, with its adjusted EBITDA margin improving to -0.2%. Zomato’s food delivery business, however, posted higher revenues (₹7,792 crore) and a positive EBITDA margin of 2.8%.  \n\nSwiggy’s IPO plans, targeting a $15 billion valuation, hinge on its ability to sustain growth and profitability amid competition from Zomato and new entrants like Amazon and Flipkart. Leadership changes and cost control strategies, including reduced advertising expenses, are part of Swiggy’s preparation for the IPO.  \n\nBoth companies are diversifying revenue streams—Swiggy through Dineout and Zomato via Paytm’s ticketing arm—while vying for dominance in India’s food-tech and quick-commerce sectors. The next few years will determine which emerges as the market leader.",
    url: "https://www.linkedin.com/pulse/swiggy-vs-zomato-food-delivery-quick-commerce-ipo-amit-varma-6skrc",
    query:
      "**Diversification and Strategic Initiatives**: How do Swiggy and Zomato differ in their diversification strategies (e.g., Swiggy Instamart vs. Zomato’s Hyperpure and Blinkit acquisition)? What impact do these initiatives have on their long-term growth potential?",
  },
  {
    sourceType: "web",
    title: "Zomato: Evolution, Strategy, and Market Leadership",
    description:
      "Founded in 2008 by Deepinder Goyal and Pankaj Chaddah, Zomato has grown from a restaurant discovery platform to a global food delivery giant. Initially named FoodieBay, it rebranded to Zomato to avoid confusion with eBay. By 2015, Zomato entered food delivery, achieving unicorn status in 2018 and going public in 2021 with an $8 billion valuation. Today, Zomato offers food delivery, dining-out services, and quick commerce through Blinkit, which it acquired in 2022.  \n\nZomato’s competitive edge lies in its reliability, extensive restaurant network, and first-mover advantage. With over 276,000 restaurant partners, it ensures quick delivery (average 12.5 minutes) and high fulfillment accuracy (99%). Its focus on service quality has led to customer willingness to pay delivery fees, boosting profitability.  \n\nThe Indian food services market, valued at ₹5.5 lakh crores, is growing at an 18% CAGR for online delivery, with Zomato holding a 55% market share. Zomato’s quick commerce arm, Blinkit, commands 45% of its market, offering ultra-fast delivery in under 15 minutes.  \n\nZomato’s revenue model includes delivery fees, restaurant commissions, and B2B supplies through Hyperpure. In FY 2023-24, Zomato generated ₹13,545 crores in revenue, a 50% YoY increase, with food delivery contributing ₹32,224 crores in Gross Order Value (GOV).  \n\nTo drive growth, Zomato leverages organic channels, paid ads, and partnerships with platforms like IRCTC and PhonePe. It also focuses on customer engagement through initiatives like Zomato Social, which integrates peer recommendations into the app. Retention strategies target aspirers, who exhibit higher order frequency and willingness to pay.  \n\nZomato’s monetization strategy includes delivery fees, restaurant commissions, and subscription programs like Zomato X, aimed at increasing order frequency and customer loyalty. With a strong presence in India’s metro cities and innovative campaigns, Zomato continues to dominate the food delivery and quick commerce markets.",
    url: "https://growthx.club/blog/zomato-business-model",
    query:
      "**Diversification and Strategic Initiatives**: How do Swiggy and Zomato differ in their diversification strategies (e.g., Swiggy Instamart vs. Zomato’s Hyperpure and Blinkit acquisition)? What impact do these initiatives have on their long-term growth potential?",
  },
  {
    sourceType: "web",
    title: "Swiggy vs Zomato: IPO, Models, and Market Lessons",
    description:
      "Swiggy is gearing up for its 11,664 crore IPO amidst challenges, while Zomato has seen a 120% stock price surge in the past year, driven by its data-driven expansion into quick commerce with Blinkit. Blinkit, now 40-50% the size of Zomato, is poised to outgrow its parent company, showcasing the power of leveraging data for scalable innovation.  \n\nSwiggy operates as a super app, offering multiple services like food delivery and groceries under one infrastructure, reducing customer acquisition costs and boosting user retention. Its hub-and-spoke delivery model optimizes routes and lowers costs, potentially saving over 400 crores annually. However, Swiggy faces scalability challenges, leadership turnover, and market preferences for specialized apps over super apps, unlike China.  \n\nZomato, on the other hand, expanded early into smaller cities, gaining market share and achieving profitability with a 43 crore adjusted EBITDA. Swiggy's revenue grew by 36%, but it remains unprofitable, with executive departures raising concerns about stability.  \n\nKey lessons from their strategies include prioritizing data for growth, tailoring business models to market needs, improving efficiency, balancing growth with profitability, and adapting to user preferences. Swiggy's IPO funding will be crucial for marketing, acquisitions, and technology investments to sustain its innovative model and navigate challenges.  \n\nUltimately, Swiggy and Zomato highlight the importance of data-driven decisions, scalable innovation, and leadership stability in building successful businesses in competitive markets.",
    url: "https://substack.com/home/post/p-150126338?utm_campaign=post&utm_medium=web",
    query:
      "**Diversification and Strategic Initiatives**: How do Swiggy and Zomato differ in their diversification strategies (e.g., Swiggy Instamart vs. Zomato’s Hyperpure and Blinkit acquisition)? What impact do these initiatives have on their long-term growth potential?",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "The Indian food delivery market has witnessed significant growth and transformation over the past few years, largely driven by the two leading players, Zomato and Swiggy. As of 2024, these two companies have dominated the landscape, engaging in a fierce battle for market leadership. 💥\n\nThis blog delves deep into the performance of Zomato Vs. Swiggy from 2022 through mid-2024, analyzing their growth trajectories, market dynamics, key challenges, and what the future might hold for these food delivery giants. 🍽️",
    url: "https://careerswami.com/zomato-vs-swiggy-comparison-market-analysis-2022-2024/",
    query:
      "**Market Trends and Competitive Landscape**: What are the broader market trends in the Indian food delivery industry, and how are Swiggy and Zomato positioned to capitalize on these trends? Are there any emerging competitors or regulatory changes impacting their growth?",
  },
  {
    sourceType: "web",
    title: "India's Food Delivery Giants: Zomato vs. Swiggy Marketing Battle",
    description:
      'India\\\'s food delivery ecosystem is dominated by Zomato and Swiggy, two companies that have grown into household names through innovative strategies and strong branding. Zomato, founded in 2008, started as a restaurant discovery platform and later expanded into food delivery, even going public in 2021. Swiggy, launched in 2014, adopted a hyperlocal approach, diversifying into services like Swiggy Genie and Instamart to cater to urban and semi-urban markets.  \n\nSocial media marketing is a key battleground for these brands. Zomato excels with witty, meme-driven content that resonates with millennials and Gen Z, often tying into trending topics. Campaigns like "FoodForThought" and Zomato Pro membership drives highlight its casual, relatable brand personality. Swiggy, on the other hand, focuses on convenience and creativity, using Instagram reels and campaigns like "Swiggy it!" to emphasize its reliability and quick delivery services.  \n\nBoth brands leverage platforms like Instagram, Twitter, and YouTube to engage audiences. Zomato dominates with snackable, humorous content, while Swiggy uses visually appealing posts to showcase features like Instamart. Metrics reveal Zomato leads in brand recall, while Swiggy excels in customer sentiment.  \n\nChallenges such as market saturation and consumer fatigue loom, but opportunities in hyper-personalization and expansion into Tier-2 and Tier-3 cities remain. As leaders in social media marketing, Zomato and Swiggy continue to shape India\\\'s food delivery landscape, connecting consumers with culinary experiences through creative and engaging digital strategies.',
    url: "https://www.linkedin.com/pulse/zomato-vs-swiggy-battle-indias-food-delivery-market-power-bhole-n98pc",
    query:
      "**Market Trends and Competitive Landscape**: What are the broader market trends in the Indian food delivery industry, and how are Swiggy and Zomato positioned to capitalize on these trends? Are there any emerging competitors or regulatory changes impacting their growth?",
  },
  {
    sourceType: "web",
    title: "Indian Food-Tech Giants: Swiggy vs Zomato Analysis",
    description:
      "The Indian food delivery market has seen rapid growth, with Swiggy and Zomato emerging as dominant players. Both companies have expanded beyond food delivery into grocery delivery and quick-commerce, leveraging technology and strategic acquisitions to strengthen their positions. Swiggy, founded in 2014, focuses on diverse offerings like Instamart (grocery delivery) and cloud kitchens, with a strong presence in Tier 2 and Tier 3 cities. Zomato, established in 2008, has a global footprint and is known for its restaurant discovery platform, food delivery, and its acquisition of Blinkit, which bolstered its quick-commerce capabilities.  \n\nBoth companies have had successful IPOs, attracting significant investor interest. Swiggy’s IPO exceeded expectations, with analysts projecting strong growth due to its market dominance and diversification. Zomato’s 2021 IPO was also a success, with its market cap doubling since listing, driven by brand recognition and strategic acquisitions.  \n\nThe Indian food-tech market has consolidated into a duopoly, with Swiggy and Zomato leading the sector. Zomato holds a larger market share, particularly in Tier 1 cities, while Swiggy excels in underserved markets. Swiggy’s strengths lie in its diverse offerings and quick-commerce focus, while Zomato benefits from its global presence and strong brand.  \n\nBoth companies are valued highly, with Swiggy at $10.7 billion and Zomato’s market cap doubling post-IPO. Neither is profitable yet, but both are making strides toward reducing losses. Their future growth depends on scaling operations, diversifying revenue streams, and adapting to trends like quick-commerce. Investors must weigh factors like profitability, execution, and market positioning when evaluating these companies, as both are poised for long-term success in the evolving food-tech landscape.",
    url: "https://investek.in/swiggy-vs-zomato-a-comprehensive-competitive-analysis-of-indias-food-delivery-giants/",
    query:
      "**Market Trends and Competitive Landscape**: What are the broader market trends in the Indian food delivery industry, and how are Swiggy and Zomato positioned to capitalize on these trends? Are there any emerging competitors or regulatory changes impacting their growth?",
  },
  {
    sourceType: "web",
    title:
      "India's Online Food Delivery Market: Growth, Trends, and Innovations",
    description:
      "The India online food ordering and delivery market, valued at USD 28.3 billion in 2022, is projected to grow at a robust CAGR of 26.89%, reaching USD 117.01 billion by 2029. This growth is driven by increasing internet penetration, smartphone usage, and consumer demand for convenience. The COVID-19 pandemic further accelerated the sector's expansion as lockdowns boosted reliance on food delivery services.  \n\nKey players like Swiggy, Zomato, and Rebel Foods dominate the competitive landscape, offering diverse cuisines and services, including grocery and alcohol delivery. Hyperlocal expansion is a notable trend, with platforms setting up localized hubs to reduce delivery times and cater to specific neighborhood preferences. Sustainability is also gaining traction, with companies adopting eco-friendly packaging, optimizing delivery routes, and promoting ethically sourced ingredients.  \n\nTechnological advancements, such as AI-driven chatbots, data analytics, and automation, are enhancing customer experiences through personalized recommendations, real-time tracking, and contactless delivery options. Despite its rapid growth, the industry faces challenges, including regulatory issues, operational complexities, and concerns over delivery worker welfare.  \n\nAs digital infrastructure improves and consumer spending rises, the market is expected to expand into smaller cities and towns. Innovations like AI and data analytics will further streamline operations and optimize delivery services, ensuring the sector remains a key player in India's food service industry.",
    url: "https://www.businesswire.com/news/home/20240321586905/en/India-Online-Food-Ordering-and-Delivery-Market-By-Region-Competition-Forecast-and-Opportunities-2019-2029F-The-Rise-of-Hyperlocal-Delivery-Swiggy-Zomato-Uber-Eats-Dominate---ResearchAndMarkets.com",
    query:
      "**Market Trends and Competitive Landscape**: What are the broader market trends in the Indian food delivery industry, and how are Swiggy and Zomato positioned to capitalize on these trends? Are there any emerging competitors or regulatory changes impacting their growth?",
  },
  {
    sourceType: "web",
    title: "Swiggy vs Zomato: India’s Food Delivery Titans Compete",
    description:
      "India’s online food delivery market has grown rapidly, with Swiggy and Zomato emerging as dominant players. Swiggy excels in logistics and fast delivery, leveraging its extensive network and cloud kitchen expansion to offer diverse cuisines. Zomato, meanwhile, provides a comprehensive platform for restaurant discovery, reviews, table reservations, and subscription services like Zomato Gold.  \n\nSwiggy primarily earns through restaurant commissions and delivery fees, while Zomato diversifies with advertising and subscriptions. Both face challenges: Swiggy struggles with operational costs and quality consistency, while Zomato grapples with profitability and customer retention. Despite these hurdles, both companies are innovating to expand their customer base.  \n\nSwiggy focuses on tier-2 and tier-3 cities and diversifies with services like Instamart and Swiggy Genie. Zomato strengthens its position through acquisitions like Uber Eats and ventures into grocery delivery. Analysts predict Zomato’s profitability will improve, while Swiggy’s grocery delivery business shows promise.  \n\nThe future looks bright for both platforms, driven by smartphone penetration, urbanization, and evolving consumer preferences. By enhancing user experience and leveraging market trends, Swiggy and Zomato are poised to maintain their leadership in India’s dynamic food delivery landscape.",
    url: "https://markitome.com/swiggy-and-zomato/",
    query:
      "**Market Trends and Competitive Landscape**: What are the broader market trends in the Indian food delivery industry, and how are Swiggy and Zomato positioned to capitalize on these trends? Are there any emerging competitors or regulatory changes impacting their growth?",
  },
  {
    sourceType: "web",
    title: "",
    description:
      'The Rare 2001-D Mule Error Explained\n\nAuction Sales of the 2001-D Lincoln Cent Mule Error\n\nLive Events\n\nPCGS MS66RD: sold for $114,000 on June 17, 2021\n\nPCGS MS65RD: sold for $78,000 on Feb. 24, 2022\n\nPCGS MS65RD: sold for $66,000 on Aug. 24, 2022\n\nPCGS MS66RD: sold for $114,000 on Jan. 11, 2024\n\nFAQs\n\n\n\n\n\n(You can now subscribe to our\n\n(You can now subscribe to our Economic Times WhatsApp channel\n\nThere’s a penny out there that looks ordinary at first, until you flip it over, known as the 2001-D Lincoln cent mule error coin, and it is so rare that it was twice sold at auction for over $100,000, as per a report.According to a GoBankingRates report, this mistakenly produced coin was struck at the Denver Mint and has Abraham Lincoln’s face on the front, like any other penny, but the reverse side is where things get unusual: instead of the Lincoln Memorial, it has the back of a Roosevelt dime, as per the report.CoinWeek wrote that, “The 2001-D Lincoln cent mule falls in the category of Mint errors that conceivably could have been produced by mistake and released unnoticed into circulation,” as per GoBankingRates.ALSO READ: Are you falling behind? The age-by-age breakdown of how much Americans should have saved for retirement by now However, these error coins are highly prized by collectors and often get very high prices in auctions, as per the report. One of the few 2001-D Lincoln cent mule coins was sold at an auction via Heritage Auctions last year for six figures, and it is the fourth such coin to sell at auction, reported CoinWeek. While Heritage Auctions has previously sold the other three at high prices, as per the report.GoBankingRates wrote, "When you include the four mentioned above, the total might not reach double figures. Because they’re so hard to find, even those in poor condition can fetch up to $20,000."It’s a rare US penny that mistakenly has a Roosevelt dime’s reverse side instead of the Lincoln Memorial.Because it’s an extremely rare mint error. Only a few are known to exist, making it highly desirable among collectors.',
    url: "https://m.economictimes.com/news/international/us/that-lincoln-penny-in-your-drawer-might-be-worth-100000-if-it-has-this-rare-mint-error-on-the-back-us-news/articleshow/121579337.cms",
    query: "News Articles: Economic Times, Mint (2023)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      'Live Events\n\n\n\n\n\n(You can now subscribe to our\n\n(You can now subscribe to our Economic Times WhatsApp channel\n\nThe U.S. Treasury may have stopped producing pennies to save an estimated $56 million, but before you clean out your coin jar, take a closer look—one of those copper coins could be worth a fortune.As reported by the GOBankingRates, a rare 2001-D Lincoln penny has become one of the most valuable error coins in circulation. Known as a "mule error", it was mistakenly minted with the reverse side of a Roosevelt dime. This coin features Abraham Lincoln’s portrait on the front and a Roosevelt dime design on the back—a bizarre and highly prized combination among collectors.Fewer than ten of these mule coins are believed to exist, making them exceptionally rare. Even in worn condition, one could fetch $20,000 or more. In top condition, they’ve shattered records. As per CoinWeek, four auctions took place so far:PCGS MS66RD: Sold for $114,000 on June 17, 2021PCGS MS65RD: Sold for $78,000 on February 24, 2022PCGS MS65RD: Sold for $66,000 on August 24, 2022PCGS MS66RD: Sold again for $114,000 on January 11, 2024All four were auctioned by Heritage Auctions, which called the coin “spectacularly rare.”The 2001-D mule penny was struck at the Denver Mint, and the origin of the error remains a mystery. While some speculate it was a genuine mistake, others debate whether the mix-up was intentional. Similar errors in the past include proof coins struck over outdated designs, coins missing inscriptions, and even coins minted on everyday objects.Still, whether by accident or oversight, these few mule coins slipped into circulation—and now they’re worth a small fortune. So next time you spot a penny, don’t be so quick to ignore it. You might just be holding a six-figure mistake.',
    url: "https://m.economictimes.com/news/international/global-trends/dont-toss-your-penniesone-could-be-worth-100000/articleshow/121577258.cms",
    query: "News Articles: Economic Times, Mint (2023)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Budget\n\nThe Union Budget contains details about the estimated receipts and the expenditure of the government for a particular fiscal year. The Budget is allotted for the upcoming fiscal year, which runs from 1st April to 31st March of the next year. Here is a quick guide on how the Union Budget is prepared",
    url: "https://www.livemint.com/topic/the-economic-times",
    query: "News Articles: Economic Times, Mint (2023)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Fintel reports that on April 7, 2025, Morgan Stanley downgraded their outlook for Jefferies Financial Group (BMV:JEF) from Overweight to Equal-Weight.\n\nWhat is the Fund Sentiment?\n\nThere are 716 funds or institutions reporting positions in Jefferies Financial Group. This is an decrease of 3 owner(s) or 0.42% in the last quarter. Average portfolio weight of all funds dedicated to JEF is 0.30%, an increase of 17.10%. Total shares owned by institutions decreased in the last three months by 4.99% to 217,492K shares.\n\nWhat are Other Shareholders Doing?\n\nSumitomo Mitsui Financial Group holds 9,247K shares representing 4.48% ownership of the company. No change in the last quarter.\n\nCitigroup holds 7,995K shares representing 3.88% ownership of the company. In its prior filing, the firm reported owning 1,607K shares , representing an increase of 79.90%. The firm increased its portfolio allocation in JEF by 189.16% over the last quarter.\n\nAllspring Global Investments Holdings holds 6,166K shares representing 2.99% ownership of the company. In its prior filing, the firm reported owning 6,511K shares , representing a decrease of 5.60%. The firm increased its portfolio allocation in JEF by 25.85% over the last quarter.\n\nAlliancebernstein holds 5,989K shares representing 2.90% ownership of the company. In its prior filing, the firm reported owning 2,312K shares , representing an increase of 61.40%. The firm increased its portfolio allocation in JEF by 159.35% over the last quarter.\n\nInvesco holds 5,294K shares representing 2.57% ownership of the company. In its prior filing, the firm reported owning 4,166K shares , representing an increase of 21.30%. The firm decreased its portfolio allocation in JEF by 85.99% over the last quarter.\n\nFintel is one of the most comprehensive investing research platforms available to individual investors, traders, financial advisors, and small hedge funds.\n\nOur data covers the world, and includes fundamentals, analyst reports, ownership data and fund sentiment, options sentiment, insider trading, options flow, unusual options trades, and much more. Additionally, our exclusive stock picks are powered by advanced, backtested quantitative models for improved profits.\n\nClick to Learn More\n\nThis story originally appeared on Fintel.\n\nThe views and opinions expressed herein are the views and opinions of the author and do not necessarily reflect those of Nasdaq, Inc.",
    url: "https://www.nasdaq.com/articles/morgan-stanley-downgrades-jefferies-financial-group-bmv-jef",
    query: "Analyst Reports: Morgan Stanley, Jefferies (2023)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "About StockTargetAdvisor.com (STA Research): Is a Canadian investment research company specializing in advanced stock research and analysis. Our research team comprises of Financial Professionals.\n\nAnalyst Coverage Update\n\nJefferies has revised its target price for Morgan Stanley from $151 to $137, reflecting concerns about the company’s future growth prospects amid broader market challenges. The decision comes as Jefferies raises red flags about several potential risks that could weigh on Morgan Stanley’s performance in the coming quarters.\n\nOne of the primary concerns cited by Jefferies is the slowdown in capital markets activity, which has significantly impacted investment banks across the industry. The firm highlights the sharp decline in trading volumes, particularly in the equities and fixed-income sectors, as investors remain cautious due to uncertainty surrounding global economic conditions. This slowdown is expected to pressure Morgan Stanley’s trading revenue, a key driver of its earnings.\n\nJefferies points out the challenges in wealth management and investment management businesses. The wealth management industry is facing headwinds, such as rising inflation, market volatility, and the potential for economic slowdowns, all of which could dampen client demand for investment products and services. These challenges are particularly significant for Morgan Stanley, given that wealth management is one of its largest and most profitable divisions. A decline in assets under management (AUM), which often correlates with market performance, could also result in lower fee income for the firm.\n\nThe investment management side of Morgan Stanley’s business also faces difficulties, with asset managers grappling with market uncertainty and shifting investor preferences. The firm’s investment management unit, which relies on managing institutional and retail investor portfolios, may experience lower growth in AUM or a rise in outflows as risk-averse investors pull back from more aggressive investment strategies amid concerns about the economic outlook.\n\nDespite these challenges, Jefferies maintains that Morgan Stanley’s underlying business model, including its diversified revenue streams, positions it to weather the storm better than some of its peers. However, the analysts note that the company’s earnings growth may be tempered by these macroeconomic pressures, and they have adjusted their target price to $137, reflecting a more cautious outlook for the bank.\n\nOutlook\n\nThe cut in Morgan Stanley’s target price from $151 to $137 by Jefferies underscores the growing concerns around the slowdown in capital markets and the headwinds facing both its wealth management and investment management businesses. These risks, coupled with broader market volatility, are expected to challenge Morgan Stanley’s ability to deliver strong earnings growth in the near future. Jefferies’ revised price target reflects these challenges and the caution surrounding the bank’s near-term prospects.",
    url: "https://www.theglobeandmail.com/investing/markets/stocks/MS/pressreleases/31796983/morgan-stanley-jefferies-reduces-valuation-on-growth-concerns/",
    query: "Analyst Reports: Morgan Stanley, Jefferies (2023)",
  },
  {
    sourceType: "web",
    title:
      "Jefferies Financial Gr: Analyst Ratings and Financial Performance Overview",
    description:
      "Jefferies Financial Group (NYSE:JEF) has received mixed analyst ratings over the past quarter, ranging from bullish to bearish. Recent data shows one bullish and two somewhat bullish ratings in the last 30 days, with no bearish sentiments. Analysts have set a 12-month price target averaging $64.75, down 14.52% from the previous $75.75, with a high estimate of $81.00 and a low of $41.00.  \n\nKey analyst actions include Goldman Sachs raising its price target to $62.00, while Morgan Stanley downgraded its rating from Overweight to Equal-Weight and lowered its price target from $81.00 to $41.00. These adjustments reflect evolving market conditions and company performance.  \n\nJefferies operates in two segments: Investment Banking and Capital Markets, its primary revenue driver, and Asset Management, which provides alternative investment services. The company faces challenges in financial health, including a -3.1% revenue decline over three months, a net margin of 5.17%, and below-average returns on equity (1.26%) and assets (0.19%). However, its debt-to-equity ratio of 2.31 indicates a sound financial structure.  \n\nAnalysts determine ratings by analyzing financial statements, attending company meetings, and forecasting metrics like growth and earnings. While these ratings provide valuable insights, investors should consider them alongside other financial indicators.  \n\nJefferies' market performance reflects industry challenges, with below-benchmark growth and profitability metrics. Investors are encouraged to monitor analyst updates and financial trends to make informed decisions.",
    url: "https://www.nasdaq.com/articles/expert-outlook-jefferies-financial-gr-through-eyes-4-analysts",
    query: "Analyst Reports: Morgan Stanley, Jefferies (2023)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Our Market Insights cover a broad range of topics, from consumer goods to technology to automobiles. We provide you with an easy-to-use yet thorough look into the future of every industry, featuring detailed forecasts for up to 5 years. To do so, we cover 1,000+ markets, including KPIs such as revenue, users, and market shares across 190+ geographical entities.",
    url: "https://www.statista.com/outlook/",
    query: "Industry Reports: RedSeer, Statista (2023)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Why Statista\n\nSee why Statista is the trusted choice for reliable data and insights. We provide one platform to simplify research and support your strategic decisions. Learn more",
    url: "https://www.statista.com/studies-and-reports/industries-and-markets",
    query: "Industry Reports: RedSeer, Statista (2023)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Jun 5, 2025 | Brands & Leaders\n\nBrand value of the most valuable brands worldwide 2025\n\nApple retained its position as the world’s most valuable brand in 2025, with an estimated brand value of nearly 1.3 trillion U.S. dollars. Google ranked second, having been valued at 944 billion dollars. Overall, the brand ranking was dominated by U.S.-based tech companies.\n\n\n\n\n\nApple’s brand is synonymous with simplicity and innovation\n\nApple is a California-based technology titan specializing in consumer electronics, software, and online services. According to the company’s latest filings, Apple’s global revenue reached 391 billion U.S. dollars in 2024, with the iPhone being its most profitable operating segment. In addition to its signature smartphone, Apple’s other breakthrough products include the Mac computer, iPad tablet, and Apple Watch, all of which are continuously updated to match consumer needs and preferences.\n\n\n\n\n\nNvidia Climbs into the Top 5 as AI Boom Accelerates\n\nA leading force in artificial intelligence, Nvidia reached the top five most valuable global brands for the first time in 2025. Behind the chips driving many of today’s generative AI applications, Nvidia is among the leading tech companies in terms of market capitalization, with a valuation of over three trillion U.S. dollars.",
    url: "https://www.statista.com/",
    query: "Industry Reports: RedSeer, Statista (2023)",
  },
  {
    sourceType: "web",
    title: "Statista: Data-Driven Insights and Market Solutions",
    description:
      "Statista is a comprehensive platform offering reliable data and insights to support strategic decision-making. It provides access to over 1 million facts across 170 industries in 150+ countries, covering consumer behavior, market forecasts, political topics, and more. Statista R collaborates with global media brands to rank industry leaders and exceptional brands.  \n\nThe platform also offers tailored services through Statista+, combining expertise in research, strategy, and marketing communications to drive success in the data-driven economy. Users can access detailed statistics, market insights, and forecasts for over 1,000 markets in 190+ countries.  \n\nStatista provides flexible account options, including free, starter, and professional plans, with premium features like downloadable statistics in various formats and access to detailed source references. The platform supports businesses with tools for content marketing, design, and strategy development.  \n\nFor personalized features like marking favorite statistics or setting alerts, users must create individual accounts. Premium users benefit from real-time updates and comprehensive data for presentations and reports. Pricing starts at $2,388 annually for full access.  \n\nStatista is a trusted resource for businesses seeking data-driven solutions and insights to navigate the global market effectively.",
    url: "https://www.statista.com/statistics/1426284/india-content-breadth-of-sfv-market-by-genre/",
    query: "Industry Reports: RedSeer, Statista (2023)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Document Information click to expand document information\n\nSwiggy is an online platform offering on-demand food and grocery delivery services in India. Founded in 2014, it has raised $3.6 billion in funding to date. Swiggy allows users to discover restaurants, order meals, and has expanded into grocery delivery. It competes with companies like Zomato, Zepto, and Blinkit in India's food delivery market.",
    url: "https://www.scribd.com/document/704701942/Swiggy-Tracxn-Company-Report-27-Dec-2023",
    query: "Swiggy FY23 Financial Disclosures (via Tracxn)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Company Details Online platform for food ordering, grocery and parcel delivery. It is an online platform that offers food and grocery delivery services, partnering with restaurants and stores. It also provides table booking services through dineout.The platform enables users to discover restaurants, dine in, and order food. It allows users to order groceries such as fruits, vegetables, beverages, meat, seafood, and more. It also allows users to deliver parcels for different locations. Website www.swiggy.com/ Social Email ID *****@swiggy.in Phone Number +91 **********",
    url: "https://tracxn.com/d/companies/swiggy/__8L46lNfjqGM9DHz7xSR4zs7iWwa57QNKLZaVbfNa3T4",
    query: "Swiggy FY23 Financial Disclosures (via Tracxn)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Swiggy, a major player in India’s food delivery and quick commerce market, has reported robust financial figures as it prepares for its upcoming Initial Public Offering (IPO). The Bengaluru-based company's operating revenue grew by 36 percent to Rs 11,247 crore in FY24, according to documents shared with its investors. Despite the growth, Swiggy managed to reduce its losses by 44 percent to Rs 2,350 crore during the same period. These numbers, though not yet audited, were first reported by The Arc.\n\nIn the first three-quarters of FY24, Swiggy posted a revenue of Rs 5,476 crore, with a reported loss of Rs 1,600 crore. The company has also attracted strategic investments from Amitabh Bachchan's family offices and Hindustan Composites, positioning itself for further growth in the Indian retail and food delivery markets.\n\nSwiggy’s core food delivery business grew by 17 percent to reach Rs 6,100 crore in FY24. Its quick commerce arm, Instamart, contributed Rs 1,100 crore in gross revenue for the same period. Despite these gains, Swiggy faces competition in the quick commerce segment, where Blinkit, owned by Zomato, holds the largest market share. According to a report from USB, Blinkit leads the market, followed by Swiggy Instamart, Zepto, and BigBasket.\n\nIn comparison, Zomato’s overall revenue for FY24 surged by 71 percent to Rs 12,114 crore. Of this, Rs 6,161 crore came from its food delivery business, while Blinkit added Rs 2,301 crore from quick commerce.\n\nSwiggy, which became part of the Decacorn club after its last equity funding round in January 2022, filed for its IPO through a confidential route in May. The company plans to raise up to Rs 3,750 crore via a fresh issue of equity shares and an offer for sale totaling up to Rs 6,664 crore.\n\nAs the IPO approaches, Swiggy's financial performance will continue to be closely watched, especially as it competes with Zomato in both the food delivery and quick commerce sectors in India.",
    url: "https://www.restaurantindia.in/news/swiggy-demonstrates-strong-financial-performance-ahead-of-ipo.n11648?page=40",
    query: "Swiggy FY23 Financial Disclosures (via Tracxn)",
  },
  {
    sourceType: "web",
    title: "CCI Flags Anti-Competitive Practices by Zomato and Swiggy",
    description:
      "The Competition Commission of India (CCI) has investigated allegations against food delivery platforms Zomato and Swiggy for anti-competitive practices that may harm India’s retail and hospitality markets. The probe, initiated after a 2022 complaint by the National Restaurant Association of India (NRAI), focused on claims of preferential treatment for certain restaurant partners and restrictive price parity clauses. These clauses prevent restaurants from offering lower prices or higher discounts on their own platforms or other aggregators, potentially creating an uneven playing field.\n\nThe CCI’s Director General submitted a report earlier this year, which flagged concerns about platforms favoring restaurant partners in which they hold equity or revenue stakes. Such practices could influence search rankings, delivery management, and other critical areas, disadvantaging competitors. The NRAI reviewed a redacted version of the report in March 2024 and has petitioned the High Court for access to the full document, citing the need to protect market interests.\n\nNRAI President Sagar Daryani expressed optimism about the investigation’s progress and urged the CCI to expedite its review of additional issues raised in the 2022 petition. He emphasized the importance of fostering equitable growth in India’s hospitality sector to support the country’s $5 trillion economic target. Swiggy disclosed the ongoing CCI case in its prospectus for a recent IPO.\n\nThe NRAI remains committed to promoting fair competition and has refrained from commenting on the confidential findings of the DG report. The association initially raised concerns in 2021, prompting the CCI to investigate exclusivity agreements and other practices that may hinder market fairness. Hearings are expected before the CCI issues its final decision.",
    url: "https://www.restaurantindia.in/news/swiggy-to-deliver-largest-secondary-exit-worth-300-million-to-investors.n17147?page=31",
    query: "Swiggy FY23 Financial Disclosures (via Tracxn)",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "Download now\n\nDownload now Download\n\nDownload now Download\n\nDownload now Download",
    url: "https://www.scribd.com/document/759240927/Zomato-Annual-Report-2023-24",
    query: "Zomato FY23 Annual Report",
  },
  {
    sourceType: "web",
    title: "",
    description:
      "ZOMATO has announced its results for the year ended March 2024. Let us have a look at the detailed performance review of the company during FY23-24.\n\n* Results Consolidated\n\nInterim results exclude extraordinary / exceptional items\n\nSource: Accord Fintech, Equitymaster\n\nLast Week: This Normally Costs Rs 40,000... But Today Only Rs 9,950*\n\n* Results Consolidated\n\nInterim results exclude extraordinary / exceptional items\n\nSource: Accord Fintech, Equitymaster\n\n* Results Consolidated\n\nInterim results exclude extraordinary / exceptional items\n\nSource: Accord Fintech, Equitymaster\n\n* Results Consolidated\n\nInterim results exclude extraordinary / exceptional items\n\nSource: Accord Fintech, Equitymaster\n\nSolvency Ratios\n\nCurrent Ratio: The company's current ratio deteriorated and stood at 2.6x during FY24, from 7.5x during FY23. The current ratio measures the company's ability to pay short-term and long-term obligations.\n\nInterest Coverage Ratio: The company's interest coverage ratio improved and stood at 5.0x during FY24, from -19.7x during FY23. The interest coverage ratio of a company states how easily a company can pay its interest expense on outstanding debt. A higher ratio is preferable.\n\nProfitability Ratios\n\nReturn on Equity (ROE): The ROE for the company improved and stood at 1.8% during FY24, from -5.3% during FY24. The ROE measures the ability of a firm to generate profits from its shareholders capital in the company.\n\nReturn on Capital Employed (ROCE): The ROCE for the company improved and stood at 1.8% during FY24, from -5.3% during FY23. The ROCE measures the ability of a firm to generate profits from its total capital (shareholder capital plus debt capital) employed in the company.\n\nReturn on Assets (ROA): The ROA of the company improved and stood at 1.8% during FY24, from -4.3% during FY23. The ROA measures how efficiently the company uses its assets to generate earnings.",
    url: "https://www.equitymaster.com/research-it/annual-results-analysis/ZOMA/ZOMATO-2023-24-Annual-Report-Analysis/10921",
    query: "Zomato FY23 Annual Report",
  },
];

export const deep_internal_sources = [
  {
    sourceType: "internal",
    title:
      '"Provide an analysis of Swiggy\\\'s performance compared to Zomato in terms of operational efficiency and financial metrics, and explain which company has greater growth potential."',
    description: "SWIGGY | Initiating Coverage | Rating: ADD | TP: R",
    filename:
      "Initiating_Coverage_-_Swiggy_Rating__ADD_TP__Rs_360_-_Food_for_Thought_Groceries_on_Hold",
    page_number: 33,
    summary:
      "This page provides a comparison of services offered by Swiggy and its global peers, highlighting potential areas for expansion. It includes a detailed table of services across companies and notes on Swiggy's current initiatives.",
  },
  {
    sourceType: "internal",
    title:
      '"Provide an analysis of Swiggy\\\'s performance compared to Zomato in terms of operational efficiency and financial metrics, and explain which company has greater growth potential."',
    description: "Business overview:\n\nSwiggy Platform visual with fo",
    filename: "swiggy_Annual-Report-2023-2024",
    page_number: 8,
    summary:
      "This page provides an overview of Swiggy's platform performance across Food Delivery, Out-of-Home Consumption, and Quick Commerce categories, along with FY24 review highlighting growth, profitability, and user metrics.",
  },
  {
    sourceType: "internal",
    title:
      '"Provide an analysis of Swiggy\\\'s performance compared to Zomato in terms of operational efficiency and financial metrics, and explain which company has greater growth potential."',
    description: "SWIGGY | Initiating Coverage | Rating: ADD | TP: R",
    filename:
      "Initiating_Coverage_-_Swiggy_Rating__ADD_TP__Rs_360_-_Food_for_Thought_Groceries_on_Hold",
    page_number: 27,
    summary:
      "This page provides a comparative analysis of Swiggy and Zomato's financial performance, focusing on improvements in Adjusted EBITDA as a percentage of Gross Order Value (GOV). It highlights cost optimizations, revenue improvements, and management guidance for both companies.",
  },
  {
    sourceType: "internal",
    title:
      '"Provide an analysis of Swiggy\\\'s performance compared to Zomato in terms of operational efficiency and financial metrics, and explain which company has greater growth potential."',
    description: "Food delivery platform – Zomato vs. Swiggy\n\nA hori",
    filename: "Zomato_Initiating_Coverage",
    page_number: 39,
    summary:
      "This page compares the food delivery platforms Zomato and Swiggy, featuring a horizontal bar graphic with three segments. It was generated by Avendus Spark Research for a specific user.",
  },
  {
    sourceType: "internal",
    title:
      '"Provide an analysis of Swiggy\\\'s performance compared to Zomato in terms of operational efficiency and financial metrics, and explain which company has greater growth potential."',
    description: "Zomato – Initiating Coverage Note | Rating: ADD | ",
    filename: "Zomato_Initiating_Coverage",
    page_number: 20,
    summary:
      "This page provides a comparative analysis of Zomato and Swiggy's operations, highlighting their respective services and areas of focus. It also mentions potential future growth opportunities for these companies.",
  },
  {
    sourceType: "internal",
    title:
      '"Provide an analysis of Swiggy\\\'s performance compared to Zomato in terms of operational efficiency and financial metrics, and explain which company has greater growth potential."',
    description: "Zomato – Initiating Coverage Note | Rating: ADD | ",
    filename: "Zomato_Initiating_Coverage",
    page_number: 19,
    summary:
      "This page provides an analysis of Zomato's business model, revenue mix, and performance by segments, with a comparison to Swiggy. It highlights Zomato's focus on food delivery and potential expansion into adjacent markets like grocery delivery and pickup & drop services.",
  },
];
